"""
One-shot prose measurement over the pinned corpus in `corpus.lock`.

Research script, not product code: Python + stdlib only (`ast`, `tokenize`,
`difflib`, `dataclasses`). Zero third-party imports on purpose — AC4 (a re-run
must be byte-identical) must not depend on dependency resolution. The product
is Rust and lives elsewhere.

Usage:
    uv run python3 corpus/measure.py --lock corpus/corpus.lock

Stdout is the report and is deterministic: sorted iteration everywhere, no
timestamps, no absolute paths, fixed float formatting. Diagnostics go to stderr.

Determinism is per-interpreter, and that is enforced, not hoped for: see
MIN_INTERPRETER below. Measured on CPython 3.14.6 (Darwin 25.5.0, arm64).
"""

from __future__ import annotations

import argparse
import ast
import difflib
import logging
import math
import subprocess
import sys
import tokenize
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path

LOG: logging.Logger = logging.getLogger("measure")

# The restatement probe reads NAME tokens off the code line under a comment, and PEP 701
# (Python 3.12) changed what those are: before 3.12 an f-string was ONE STRING token, so every
# identifier interpolated inside it was invisible. Measured on an audited repository, same commit,
# same block count (2033 blocks, 1035 comment blocks) — only the probe moves:
#     3.11  -> 137 restatement candidates is reported as 133, code-like 21 as 19
#     3.12+ -> 137 / 21   (identifiers inside f-strings are seen, which is the faithful reading)
# So AC4 byte-identity holds on a FIXED interpreter and not across versions. Rather than let a
# 3.11 run quietly emit different constants into REPORT.md, refuse to run at all.
MIN_INTERPRETER: tuple[int, int] = (3, 12)

# --- denominator hygiene ----------------------------------------------------
# Any path containing one of these directory components is not this repo's own
# prose: it is a virtualenv, a build artefact, vendored or generated code. A
# ratio computed over these is wrong, and every constant derived from it is
# wrong with it. The list is reproduced verbatim in REPORT.md.
EXCLUDED_DIRS: frozenset[str] = frozenset(
    {
        ".git",
        ".venv",
        "venv",
        "env",
        ".env",
        ".tox",
        ".nox",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        "__pycache__",
        "node_modules",
        "target",
        "build",
        "dist",
        "site-packages",
        ".eggs",
        "vendor",
        "_vendor",
        "third_party",
        "thirdparty",
        "migrations",
        ".idea",
        ".vscode",
    }
)
EXCLUDED_SUFFIXES: tuple[str, ...] = ("_pb2.py", "_pb2_grpc.py", ".pyi")
# Machine-written headers: protoc, Stainless, openapi-generator, datamodel-codegen.
GENERATED_MARKERS: tuple[str, ...] = (
    "do not edit",
    "generated by",
    "autogenerated",
    "auto-generated",
    "@generated",
    "code generated by",
)
GENERATED_SCAN_LINES: int = 6

SHINGLE_K: int = 3
# Candidate generation caps the inverted index: a shingle shared by more than
# this many blocks is boilerplate ("args returns none") and its bucket is
# quadratic. Exact duplicates are found by grouping instead, uncapped, so the
# `"""Initialize the class."""` phenomenon is still counted exactly.
# ponytail: hard cap instead of minhash/LSH; this is a one-shot measurement, the
# product-side sublinear candidate generation is the Rust task's problem.
MAX_SHINGLE_DF: int = 40
# difflib is O(n*m) per pair: only a deterministic prefix of the sorted pair
# list is scored with it, purely to compare the two metrics.
DIFFLIB_SAMPLE: int = 2000

RESTATEMENT_STOPWORDS: frozenset[str] = frozenset(
    {
        "a",
        "an",
        "and",
        "are",
        "as",
        "at",
        "be",
        "but",
        "by",
        "can",
        "for",
        "from",
        "get",
        "if",
        "in",
        "into",
        "is",
        "it",
        "its",
        "not",
        "of",
        "on",
        "or",
        "so",
        "than",
        "that",
        "the",
        "then",
        "there",
        "these",
        "this",
        "to",
        "up",
        "use",
        "used",
        "we",
        "when",
        "which",
        "will",
        "with",
    }
)
RESTATEMENT_MIN_TOKENS: int = 2
RESTATEMENT_OVERLAP: float = 0.5

JACCARD_GRID: tuple[float, ...] = (0.5, 0.6, 0.75, 0.9, 1.0)
MIN_SIZE_GRID: tuple[int, ...] = (1, 2, 3, 4, 5)
# The same grid in WORDS, because physical lines turn out not to separate
# boilerplate from substance: a 3-word `Init API instance.` docstring written
# across three physical lines passes any line-based cutoff of 3.
MIN_WORD_GRID: tuple[int, ...] = (4, 6, 8, 10, 12, 16)
CALIBRATION_THRESHOLD: float = 0.75
# Candidate min-block-size cutoffs as (min physical lines, min normalised words).
# Neither dimension works alone: words alone let one-line copy-paste back in
# (palette URLs, pytest `# Arrange` markers), lines alone let a 3-word
# `Init API instance.` spread over three lines through.
CONJUNCTION_CUTOFFS: tuple[tuple[int, int], ...] = ((1, 1), (2, 6), (2, 8), (2, 10), (2, 12), (2, 16), (3, 8), (3, 12))
TAIL_TOP_N: int = 10
BIG_BLOCK_LINES: tuple[int, ...] = (10, 20, 55)


@dataclass(frozen=True)
class ProseBlock:
    """One prose block: a docstring, or a run of own-line `#` comments."""

    kind: str
    rel_path: str
    start_line: int
    end_line: int
    normalised: str
    raw: str

    @property
    def size_lines(self) -> int:
        """Physical line span — the unit the issue measured 7/55 in."""
        return self.end_line - self.start_line + 1

    @property
    def size_words(self) -> int:
        """Normalised word count — the rival unit for the min-size cutoff."""
        return len(self.normalised.split())


@dataclass(frozen=True)
class RestatementHit:
    """One comment block whose words mostly re-appear in the code below it."""

    rel_path: str
    line: int
    comment: str
    code_line: str
    code_like: bool


@dataclass
class FileStats:
    """
    Line buckets and prose blocks of a single `.py` file.

    `prose_lines + blank_lines + code_lines == total_lines` by construction:
    every physical line lands in exactly one bucket, prose winning over blank
    (a blank line inside a docstring is docstring, not whitespace).
    """

    rel_path: str
    total_lines: int
    prose_lines: int
    blank_lines: int
    code_lines: int
    trailing_comments: int
    blocks: list[ProseBlock] = field(default_factory=list)
    restatement_hits: list[RestatementHit] = field(default_factory=list)

    @property
    def docstring_sizes(self) -> list[int]:
        """Physical sizes of this file's docstrings, in source order."""
        return [b.size_lines for b in self.blocks if b.kind == "docstring"]

    @property
    def comment_block_sizes(self) -> list[int]:
        """Physical sizes of this file's own-line comment blocks."""
        return [b.size_lines for b in self.blocks if b.kind == "comment"]

    @property
    def prose_share(self) -> float:
        """
        Prose lines over ALL physical lines. 0.0 for an empty file.

        This denominator, not the non-blank one, is the definition that
        reproduces the issue's published figures: it gives 47.4 / 53.0 / 41.7%
        for the three files the issue names, where the
        issue reports 48 / 53 / 42%. Downstream tasks must compare against the
        issue, so the issue's denominator wins.
        """
        return self.prose_lines / self.total_lines if self.total_lines else 0.0

    @property
    def prose_share_nonblank(self) -> float:
        """Prose lines over non-blank lines — the stricter, secondary view."""
        denom: int = self.total_lines - self.blank_lines
        return self.prose_lines / denom if denom else 0.0


@dataclass
class RepoStats:
    """Everything REPORT.md quotes about one corpus entry."""

    name: str
    url: str
    sha: str
    available: bool
    files: list[FileStats] = field(default_factory=list)
    skipped_unparsable: int = 0
    skipped_generated: int = 0
    restatement_candidates: int = 0
    restatement_code_like: int = 0
    comment_blocks_examined: int = 0

    @property
    def measurable(self) -> bool:
        """Contributes numbers only if checked out AND holding Python files."""
        return self.available and bool(self.files)

    @property
    def status_note(self) -> str:
        """Why a repo contributes no numbers — reported, never silently zero."""
        if not self.available:
            return "UNAVAILABLE (could not check out this pin)"
        if not self.files:
            return "NO PYTHON FILES at this pin"
        return "measured"


def percentile(values: list[int], p: int) -> int:
    """
    Nearest-rank percentile: rank = ceil(p/100 * n), 1-indexed.

    Discrete on purpose — REPORT.md quotes physical line counts, and an
    interpolated 9.1 lines is not a thing anyone can act on. Empty -> 0.
    """
    if not values:
        return 0
    ordered: list[int] = sorted(values)
    rank: int = max(1, math.ceil(p / 100 * len(ordered)))
    return ordered[min(rank, len(ordered)) - 1]


def normalise(text: str) -> str:
    """
    Lowercase, drop every non-alphanumeric char, collapse whitespace.

    Kills the difference between a `# Foo bar.` comment and a triple-quoted
    `foo   bar` docstring, so the same sentence written in either place compares
    equal. That is the point: the duplicate detector must not care which syntax
    carried the sentence. Unicode
    letters survive (`str.isalnum`), so Russian prose is normalised too.
    """
    kept: list[str] = [ch.lower() if ch.isalnum() else " " for ch in text]
    return " ".join("".join(kept).split())


def shingles(normalised: str) -> frozenset[tuple[str, ...]]:
    """Word shingles of width `SHINGLE_K`; shorter texts yield one short gram."""
    words: list[str] = normalised.split()
    if len(words) < SHINGLE_K:
        return frozenset({tuple(words)}) if words else frozenset()
    return frozenset(tuple(words[i : i + SHINGLE_K]) for i in range(len(words) - SHINGLE_K + 1))


def jaccard(a: frozenset[tuple[str, ...]], b: frozenset[tuple[str, ...]]) -> float:
    """Score |A n B| / |A u B|; 0.0 if either side is empty."""
    if not a or not b:
        return 0.0
    union: int = len(a | b)
    return len(a & b) / union if union else 0.0


def looks_like_code(raw: str) -> bool:
    """
    Report whether a comment body parses as Python — i.e. it is commented-out code.

    This separates a real restatement (`# increment counter`) from a disabled
    statement (`# print(df, file_path)`). The distinction is not cosmetic: the
    issue puts commented-out code Out of scope because `ruff ERA001` already
    owns it, so every hit in this class is a false positive for detector 2.
    """
    body: str = raw.strip()
    if not body:
        return False
    # A commented-out block opener (`# if lock:`, `# for row in rows:`) has its body on other
    # lines, so it does not parse on its own. Retry it with a synthetic body — without this,
    # every disabled `if`/`for`/`while`/`with` was scored as prose.
    attempts: tuple[str, ...] = (body, f"{body}\n    pass") if body.endswith(":") else (body,)
    for source in attempts:
        try:
            tree: ast.Module = ast.parse(source)
        except (SyntaxError, ValueError, MemoryError, RecursionError):
            continue
        for node in tree.body:
            if isinstance(node, ast.Expr) and _is_prose_expression(node.value):
                continue
            return True
    return False


# Leaves a phrase can be built from, and the operators that can join them. A slash- or
# dash-joined phrase (`source / destination`) parses as an expression but is prose.
_PROSE_LEAVES: tuple[type[ast.AST], ...] = (ast.Name, ast.Constant)
_PROSE_OPERATORS: tuple[type[ast.AST], ...] = (ast.BinOp, ast.UnaryOp, ast.BoolOp, ast.Compare)


def _is_prose_expression(node: ast.expr) -> bool:
    """
    Report whether an expression is a phrase rather than a statement worth running.

    Both directions of this call move the pivotal commented-out share behind decision 1, so
    both were wrong before (review finding A4):

    * `source / destination` above `copy(source, destination)` is a restatement. Its `BinOp`
      was scored as code, which INFLATED the commented-out count and made detector 2 look
      worse than it is. Operator-joined phrases over plain leaves are prose.
    * `config.retry_limit` above `if config.retry_limit:` is a disabled statement. Its
      `Attribute` was exempted as prose, which LOWERED the count and made detector 2 look
      cleaner. A bare attribute access is code, so `Attribute` is deliberately absent below.

    Anything with a call, subscript, comprehension or keyword in it is code either way.
    """
    if isinstance(node, _PROSE_LEAVES):
        return True
    if isinstance(node, _PROSE_OPERATORS):
        return all(_is_prose_expression(child) for child in ast.iter_child_nodes(node) if isinstance(child, ast.expr))
    return False


def _stem(word: str) -> str:
    """
    Crude suffix strip so `increments` matches `increment`.

    Deliberately not a real stemmer: this is a frequency probe for the
    restatement detector, not the detector's contract (that is task 5).
    """
    for suffix in ("ing", "ies", "ed", "es", "s"):
        if len(word) > len(suffix) + 2 and word.endswith(suffix):
            return word[: -len(suffix)]
    return word


def _is_excluded(rel_parts: tuple[str, ...]) -> bool:
    """
    Report whether a relative path is outside this repo's own hand-written prose.

    Takes the FULL parts (directories AND filename) and compares case-folded. Normalising
    before comparing, rather than after, is the point: `Vendor/` is vendored code just as
    `vendor/` is, and `pkg.egg-info/` is packaging metadata wherever the marker sits. The
    earlier version tested `.egg-info` against the *filename*, which no `.py` file is ever
    called, so those directories were measured as first-party source.
    """
    folded: tuple[str, ...] = tuple(part.casefold() for part in rel_parts)
    directories: tuple[str, ...] = folded[:-1]
    if any(part in EXCLUDED_DIRS for part in directories):
        return True
    if any(part.endswith(".egg-info") for part in directories):
        return True
    return any(folded[-1].endswith(suffix) for suffix in EXCLUDED_SUFFIXES)


def iter_python_files(root: Path) -> list[Path]:
    """
    Every non-excluded `.py` file under `root`, sorted, each real file counted once.

    Symlinks are resolved before the exclusion test and used to de-duplicate: a link named
    `src/lib.py` whose target is `vendor/lib.py` is vendored code however it is spelled, and
    two links onto one file are one file's prose, not two. A link out of the checkout belongs
    to some other tree and is not measured.
    """
    base: Path = root.resolve()
    chosen: dict[Path, Path] = {}
    for path in sorted(root.rglob("*.py")):
        if _is_excluded(path.relative_to(root).parts):
            continue
        try:
            real: Path = path.resolve(strict=True)
        except OSError:
            LOG.warning("%s: unresolvable path (broken symlink?)", path.name)
            continue
        try:
            if _is_excluded(real.relative_to(base).parts):
                continue
        except ValueError:
            continue
        prior: Path | None = chosen.get(real)
        # Prefer the real file over a link to it, so the reported path is the canonical one.
        if prior is None or (prior.is_symlink() and not path.is_symlink()):
            chosen[real] = path
    return sorted(chosen.values())


def _looks_generated(lines: list[str]) -> bool:
    """
    Report whether the first few lines carry a machine-written header.

    Anchored, not a bare substring sweep. A hand-written docstring saying "IDs are generated
    by the server" is not a generated file, and excluding it would drop a real file out of
    every denominator in the report. So a marker counts only inside a `#` comment, or at the
    very start of a line's text.
    """
    for raw in lines[:GENERATED_SCAN_LINES]:
        stripped: str = raw.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            comment: str = stripped.lstrip("#").strip().casefold()
            if any(marker in comment for marker in GENERATED_MARKERS):
                return True
            continue
        text: str = stripped.lstrip("\"'").strip().casefold()
        if any(text.startswith(marker) for marker in GENERATED_MARKERS):
            return True
    return False


def _docstring_spans(tree: ast.Module) -> list[tuple[int, int]]:
    """
    (start, end) of every docstring, module and class included.

    Module and ClassDef are in this tuple on purpose: a walk that only visits
    functions loses them, which is the `radon multi` undercount the issue hit
    (79 reported against 94 real). `test_measure.py` pins all three kinds.
    """
    spans: list[tuple[int, int]] = []
    holders: tuple[type[ast.AST], ...] = (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)
    for node in ast.walk(tree):
        if not isinstance(node, holders):
            continue
        body: list[ast.stmt] = getattr(node, "body", [])
        if not body:
            continue
        first: ast.stmt = body[0]
        if (
            isinstance(first, ast.Expr)
            and isinstance(first.value, ast.Constant)
            and isinstance(first.value.value, str)
            and first.end_lineno is not None
        ):
            spans.append((first.lineno, first.end_lineno))
    return sorted(spans)


def measure_file(path: Path, rel_path: str | None = None) -> FileStats:
    """
    Bucket every physical line of `path` and extract its prose blocks.

    Raises SyntaxError / UnicodeDecodeError / tokenize.TokenError on input the
    stdlib parser rejects; the caller counts those files instead of guessing.
    """
    rel: str = rel_path if rel_path is not None else path.name
    with tokenize.open(path) as handle:
        source: str = handle.read()
    lines: list[str] = source.splitlines()
    total: int = len(lines)
    tree: ast.Module = ast.parse(source, filename=str(path))

    # kind per 1-indexed physical line: "prose" | "blank" | "code"
    kinds: list[str] = ["code"] * (total + 1)
    for index, raw in enumerate(lines, start=1):
        if not raw.strip():
            kinds[index] = "blank"

    blocks: list[ProseBlock] = []
    for start, end in _docstring_spans(tree):
        text: str = "\n".join(lines[start - 1 : end])
        blocks.append(ProseBlock("docstring", rel, start, end, normalise(text), text))
        for line_no in range(start, min(end, total) + 1):
            kinds[line_no] = "prose"

    # Own-line comments: a COMMENT token whose line holds nothing but the
    # comment. Consecutive such lines glue into one block (the issue's
    # "склейка соседних #-строк"). Comments sharing a line with code are
    # trailing comments and counted separately — they are not blocks.
    own_line: dict[int, str] = {}
    trailing: int = 0
    line_names: dict[int, set[str]] = defaultdict(set)
    with tokenize.open(path) as handle:
        for token in tokenize.generate_tokens(handle.readline):
            if token.type == tokenize.COMMENT:
                if lines[token.start[0] - 1][: token.start[1]].strip():
                    trailing += 1
                else:
                    own_line[token.start[0]] = token.string
            elif token.type == tokenize.NAME:
                line_names[token.start[0]].add(token.string)

    for line_no in sorted(own_line):
        kinds[line_no] = "prose"
    run: list[int] = []
    for line_no in sorted(own_line) + [-1]:
        if run and line_no == run[-1] + 1:
            run.append(line_no)
            continue
        if run:
            text = "\n".join(own_line[n].lstrip("#") for n in run)
            blocks.append(ProseBlock("comment", rel, run[0], run[-1], normalise(text), text))
        run = [line_no] if line_no > 0 else []

    stats = FileStats(
        rel_path=rel,
        total_lines=total,
        prose_lines=sum(1 for k in kinds[1:] if k == "prose"),
        blank_lines=sum(1 for k in kinds[1:] if k == "blank"),
        code_lines=sum(1 for k in kinds[1:] if k == "code"),
        trailing_comments=trailing,
        blocks=sorted(blocks, key=lambda b: (b.start_line, b.end_line, b.kind)),
    )
    stats.restatement_hits = count_restatements(stats, kinds, line_names, lines)
    return stats


def count_restatements(
    stats: FileStats, kinds: list[str], line_names: dict[int, set[str]], lines: list[str]
) -> list[RestatementHit]:
    """
    Comment blocks whose words mostly re-appear as identifiers just below.

    Frequency probe for detector 2, not detector 2: `# increment counter` above
    `counter += 1` scores 1.0 and counts. Only own-line comment blocks are
    probed, English-only by construction (stems are ASCII suffixes).
    """
    hits: list[RestatementHit] = []
    for block in stats.blocks:
        if block.kind != "comment":
            continue
        words: list[str] = [
            _stem(w) for w in block.normalised.split() if w not in RESTATEMENT_STOPWORDS and not w.isdigit()
        ]
        if len(set(words)) < RESTATEMENT_MIN_TOKENS:
            continue
        target: int | None = next((n for n in range(block.end_line + 1, len(kinds)) if kinds[n] == "code"), None)
        if target is None:
            continue
        code_tokens: set[str] = {
            _stem(part.lower()) for name in line_names.get(target, set()) for part in name.split("_") if part
        }
        overlap: float = len(set(words) & code_tokens) / len(set(words))
        if overlap >= RESTATEMENT_OVERLAP:
            hits.append(
                RestatementHit(
                    rel_path=block.rel_path,
                    line=block.start_line,
                    comment=block.normalised,
                    code_line=lines[target - 1].strip(),
                    code_like=looks_like_code(block.raw),
                )
            )
    return hits


@dataclass
class DuplicateStats:
    """Duplicate-candidate counts for one repo, by metric and by cutoff."""

    blocks_total: int = 0
    exact_groups: int = 0
    exact_pairs: int = 0
    # (min_size, threshold) -> pair count, Jaccard over word shingles
    jaccard_grid: dict[tuple[int, float], int] = field(default_factory=dict)
    # same, but the cutoff is a minimum WORD count instead of a line count
    jaccard_word_grid: dict[tuple[int, float], int] = field(default_factory=dict)
    # same grid, difflib.SequenceMatcher ratio on the deterministic sample
    difflib_sampled: int = 0
    difflib_grid: dict[tuple[int, float], int] = field(default_factory=dict)
    # (min_lines, min_words, threshold) -> pair count; THE decision table
    conjunction: dict[tuple[int, int, float], int] = field(default_factory=dict)
    # metric agreement on the SAME sampled pairs, at CALIBRATION_THRESHOLD
    agree_both: int = 0
    agree_jaccard_only: int = 0
    agree_difflib_only: int = 0
    capped_shingles: int = 0
    # distinct blocks that appear in at least one over-cap bucket — the mass the cap touches
    capped_blocks: int = 0
    # highest FIRST-element block index the difflib sample reached; a lexicographic prefix
    # cannot reach the end of the sorted pair list, so this pins the sample's span
    sampled_max_left: int = 0
    candidate_pairs: int = 0
    # exact-duplicate pair counts split by the size of the duplicated block
    exact_pairs_by_size: dict[int, int] = field(default_factory=dict)
    top_exact: list[tuple[int, int, str, str]] = field(default_factory=list)


def duplicate_stats(blocks: list[ProseBlock]) -> DuplicateStats:
    """
    Rough duplicate-candidate pass: exact groups + near-dup via shingles.

    Two passes because they answer different questions. Exact grouping is cheap
    and uncapped, so the `Initialize the class.` one-liner family is counted
    precisely — that family is the whole reason a min-block-size exists. Near
    duplicates need pair scoring, so their candidates come from an inverted
    index with a document-frequency cap (`capped_shingles` reports the cost).
    """
    result = DuplicateStats(blocks_total=len(blocks))
    if not blocks:
        return result

    by_text: dict[str, list[int]] = defaultdict(list)
    for index, block in enumerate(blocks):
        if block.normalised:
            by_text[block.normalised].append(index)

    # group id per block, for blocks that have at least one exact twin. Every pair inside a
    # group scores J=1.0 by definition, so those pairs are added to the tables ARITHMETICALLY
    # below and must be excluded from the index pass to avoid double counting.
    group_of: dict[int, int] = {}
    exact_groups: list[tuple[int, int, int]] = []  # (members, size_lines, size_words)
    for text in sorted(by_text):
        group: list[int] = by_text[text]
        if len(group) < 2:
            continue
        pairs: int = len(group) * (len(group) - 1) // 2
        result.exact_groups += 1
        result.exact_pairs += pairs
        first: ProseBlock = blocks[group[0]]
        size: int = first.size_lines
        result.exact_pairs_by_size[size] = result.exact_pairs_by_size.get(size, 0) + pairs
        result.top_exact.append((len(group), size, first.rel_path, text[:60]))
        for member in group:
            group_of[member] = result.exact_groups
        exact_groups.append((len(group), size, first.size_words))
    result.top_exact = sorted(result.top_exact, key=lambda t: (-t[0], -t[1], t[2]))[:TAIL_TOP_N]

    shingle_sets: list[frozenset[tuple[str, ...]]] = [shingles(b.normalised) for b in blocks]
    index_by_shingle: dict[tuple[str, ...], list[int]] = defaultdict(list)
    for block_id, gram_set in enumerate(shingle_sets):
        for gram in gram_set:
            index_by_shingle[gram].append(block_id)

    candidates: set[tuple[int, int]] = set()
    capped_members: set[int] = set()
    for gram in sorted(index_by_shingle):
        bucket: list[int] = index_by_shingle[gram]
        if len(bucket) > MAX_SHINGLE_DF:
            result.capped_shingles += 1
            capped_members.update(bucket)
            continue
        for i in range(len(bucket)):
            for j in range(i + 1, len(bucket)):
                left_id, right_id = bucket[i], bucket[j]
                # Exact twins are counted arithmetically; skip them here or they land twice.
                if left_id in group_of and group_of[left_id] == group_of.get(right_id):
                    continue
                candidates.add((left_id, right_id))
    result.capped_blocks = len(capped_members)

    ordered_pairs: list[tuple[int, int]] = sorted(candidates)
    # Pairs actually scored into the tables: index-generated plus the exact groups.
    result.candidate_pairs = len(ordered_pairs) + result.exact_pairs
    for threshold in JACCARD_GRID:
        for min_size in MIN_SIZE_GRID:
            result.jaccard_grid[(min_size, threshold)] = 0
            result.difflib_grid[(min_size, threshold)] = 0
        for min_words in MIN_WORD_GRID:
            result.jaccard_word_grid[(min_words, threshold)] = 0
        for min_lines, min_words in CONJUNCTION_CUTOFFS:
            result.conjunction[(min_lines, min_words, threshold)] = 0

    for left, right in ordered_pairs:
        a: ProseBlock = blocks[left]
        b: ProseBlock = blocks[right]
        score: float = jaccard(shingle_sets[left], shingle_sets[right])
        smaller: int = min(a.size_lines, b.size_lines)
        fewer_words: int = min(a.size_words, b.size_words)
        for threshold in JACCARD_GRID:
            if score < threshold:
                continue
            for min_size in MIN_SIZE_GRID:
                if smaller >= min_size:
                    result.jaccard_grid[(min_size, threshold)] += 1
            for min_words in MIN_WORD_GRID:
                if fewer_words >= min_words:
                    result.jaccard_word_grid[(min_words, threshold)] += 1
            for min_lines, min_words in CONJUNCTION_CUTOFFS:
                if smaller >= min_lines and fewer_words >= min_words:
                    result.conjunction[(min_lines, min_words, threshold)] += 1

    # Exact groups, added arithmetically rather than pair-by-pair. Two reasons this is not an
    # optimisation but a correctness fix (review finding A2): with a document-frequency cap of
    # 40, 41 identical blocks put every shingle they own in an over-cap bucket, so the index
    # pass emitted NOTHING and the tables read zero while exact grouping read 820 — the
    # most-duplicated content, which is the whole point of a duplicate detector, was the content
    # most certain to disappear. And C(n,2) for a group of 800 is 320k pairs whose score is
    # known to be 1.0 without comparing anything, so scoring them individually would only buy a
    # slower run. Every pair in a group shares one text, hence one size in lines and words.
    for members, size_lines, size_words in exact_groups:
        pairs = members * (members - 1) // 2
        for threshold in JACCARD_GRID:
            for min_size in MIN_SIZE_GRID:
                if size_lines >= min_size:
                    result.jaccard_grid[(min_size, threshold)] += pairs
            for min_words in MIN_WORD_GRID:
                if size_words >= min_words:
                    result.jaccard_word_grid[(min_words, threshold)] += pairs
            for min_lines, min_words in CONJUNCTION_CUTOFFS:
                if size_lines >= min_lines and size_words >= min_words:
                    result.conjunction[(min_lines, min_words, threshold)] += pairs

    # Deterministic UNIFORM sample, not the first N: a lexicographic prefix means pairs in
    # `a_*.py` are always scored and pairs in `z_*.py` never are, so the metric comparison would
    # be drawn from one corner of the corpus (review finding B5). Evenly spaced indices that
    # INCLUDE both ends span the whole sorted range. `//` keeps it integer and reproducible;
    # a plain `[::step]` stride was not enough, because step collapses to 1 — and the sample
    # back to a prefix — whenever the pair list only just exceeds the sample size.
    total_pairs: int = len(ordered_pairs)
    if total_pairs <= DIFFLIB_SAMPLE:
        sampled_pairs: list[tuple[int, int]] = ordered_pairs
    else:
        span: int = total_pairs - 1
        last: int = DIFFLIB_SAMPLE - 1
        sampled_pairs = [ordered_pairs[k * span // last] for k in range(DIFFLIB_SAMPLE)]
    for left, right in sampled_pairs:
        a = blocks[left]
        b = blocks[right]
        ratio: float = difflib.SequenceMatcher(None, a.normalised, b.normalised).ratio()
        score = jaccard(shingle_sets[left], shingle_sets[right])
        result.difflib_sampled += 1
        result.sampled_max_left = max(result.sampled_max_left, left)
        smaller = min(a.size_lines, b.size_lines)
        for threshold in JACCARD_GRID:
            if ratio < threshold:
                continue
            for min_size in MIN_SIZE_GRID:
                if smaller >= min_size:
                    result.difflib_grid[(min_size, threshold)] += 1
        # Apples-to-apples: both metrics on the same pair, one cutoff.
        hot_jaccard: bool = score >= CALIBRATION_THRESHOLD
        hot_difflib: bool = ratio >= CALIBRATION_THRESHOLD
        if hot_jaccard and hot_difflib:
            result.agree_both += 1
        elif hot_jaccard:
            result.agree_jaccard_only += 1
        elif hot_difflib:
            result.agree_difflib_only += 1

    return result


DECIDED_MIN_LINES: int = 2
DECIDED_MIN_WORDS: int = 8


def inspect_findings(repo: RepoStats) -> list[str]:
    """
    Every surviving finding for one repo, so a precision claim is checkable.

    REPORT.md asserts a hand-classified precision on two samples. An assertion
    nobody can re-derive is worthless, so the samples are printed here rather
    than described: `--inspect <repo>` reproduces them verbatim.
    """
    out: list[str] = [
        f"# {repo.name} @ {repo.sha}",
        "",
        (
            f"## Detector-1 candidates: Jaccard >= {CALIBRATION_THRESHOLD}, "
            f">= {DECIDED_MIN_LINES} lines AND >= {DECIDED_MIN_WORDS} words"
        ),
        "",
    ]
    blocks: list[ProseBlock] = [b for f in repo.files for b in f.blocks]
    sets: list[frozenset[tuple[str, ...]]] = [shingles(b.normalised) for b in blocks]
    index: dict[tuple[str, ...], list[int]] = defaultdict(list)
    for block_id, gram_set in enumerate(sets):
        for gram in gram_set:
            index[gram].append(block_id)
    pairs: set[tuple[int, int]] = set()
    for gram in sorted(index):
        bucket: list[int] = index[gram]
        if len(bucket) > MAX_SHINGLE_DF:
            continue
        for i in range(len(bucket)):
            for j in range(i + 1, len(bucket)):
                pairs.add((bucket[i], bucket[j]))

    found: list[tuple[float, ProseBlock, ProseBlock]] = []
    for left, right in sorted(pairs):
        a: ProseBlock = blocks[left]
        b: ProseBlock = blocks[right]
        if min(a.size_lines, b.size_lines) < DECIDED_MIN_LINES:
            continue
        if min(a.size_words, b.size_words) < DECIDED_MIN_WORDS:
            continue
        score: float = jaccard(sets[left], sets[right])
        if score >= CALIBRATION_THRESHOLD:
            found.append((score, a, b))
    out.append(f"total: {len(found)}")
    out.append("")
    for number, (score, a, b) in enumerate(
        sorted(found, key=lambda t: (-t[0], t[1].rel_path, t[1].start_line)), start=1
    ):
        out.append(
            f"[{number}] J={score:.3f}  {a.rel_path}:{a.start_line} ({a.kind}, {a.size_lines}ln/{a.size_words}w)"
        )
        out.append(f"     <-> {b.rel_path}:{b.start_line} ({b.kind}, {b.size_lines}ln/{b.size_words}w)")
        out.append(f"     {a.normalised[:100]}")
    out.append("")
    out.append(f"## Detector-2 candidates: token overlap >= {RESTATEMENT_OVERLAP} with the next code line")
    out.append("")
    out.append(
        f"total: {repo.restatement_candidates}, of which "
        f"{repo.restatement_code_like} parse as Python (commented-out code, "
        f"ruff ERA001's territory -> false positives for detector 2)"
    )
    out.append("")
    hits: list[RestatementHit] = sorted(
        (h for f in repo.files for h in f.restatement_hits), key=lambda h: (h.rel_path, h.line)
    )
    for number, hit in enumerate(hits, start=1):
        tag: str = "CODE-LIKE" if hit.code_like else "prose    "
        out.append(f"[{number}] {tag} {hit.rel_path}:{hit.line}  # {hit.comment[:70]}")
        out.append(f"     -> {hit.code_line[:90]}")
    out.append("")
    return out


def read_lock(lock_path: Path) -> list[tuple[str, str]]:
    """Parse `<url> <sha>` lines; `#` comments and blanks ignored."""
    entries: list[tuple[str, str]] = []
    for raw in lock_path.read_text(encoding="utf-8").splitlines():
        line: str = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts: list[str] = line.split()
        if len(parts) != 2:
            raise ValueError(f"corpus.lock: expected '<url> <sha>', got: {raw!r}")
        entries.append((parts[0], parts[1]))
    return entries


def repo_name(url: str) -> str:
    """Last path component of the URL, `.git` stripped."""
    return url.rstrip("/").rsplit("/", 1)[-1].removesuffix(".git")


def _run(args: list[str]) -> subprocess.CompletedProcess[str]:
    """Run a git command, capturing both streams; never raises on non-zero."""
    return subprocess.run(args, capture_output=True, text=True, check=False)


def ensure_checkout(url: str, sha: str, dest: Path, mirror_dir: Path) -> bool:
    """
    Materialise `sha` of `url` at `dest`. True if the tree is ready.

    Never touches the user's working copies: a local mirror is used only as a
    read-only clone SOURCE, and every checkout happens inside `dest`, which is
    git-ignored and disposable.
    """
    if (dest / ".git").exists():
        if checkout_is_pinned(dest, sha):
            return True
        LOG.warning("%s: checkout is not exactly %s, refetching", dest.name, sha[:12])

    mirror: Path = mirror_dir / repo_name(url)
    source: str = str(mirror) if (mirror / ".git").exists() else url
    dest.mkdir(parents=True, exist_ok=True)
    for args in (["git", "-C", str(dest), "init", "-q"], ["git", "-C", str(dest), "remote", "add", "origin", source]):
        outcome: subprocess.CompletedProcess[str] = _run(args)
        if outcome.returncode != 0 and "already exists" not in outcome.stderr:
            LOG.error("%s: %s -> %s", dest.name, args[-1], outcome.stderr.strip())
            return False
    _run(["git", "-C", str(dest), "remote", "set-url", "origin", source])

    for fetch in (
        ["git", "-C", str(dest), "fetch", "-q", "--depth", "1", "origin", sha],
        ["git", "-C", str(dest), "fetch", "-q", "origin", sha],
        ["git", "-C", str(dest), "fetch", "-q", "origin"],
    ):
        if _run(fetch).returncode == 0:
            checkout: subprocess.CompletedProcess[str] = _run(["git", "-C", str(dest), "checkout", "-q", sha])
            if checkout.returncode == 0:
                # Re-verify rather than trust the exit code: this is the assertion the whole
                # AC4 claim rests on, so it is made once, in one place, for both paths.
                if checkout_is_pinned(dest, sha):
                    return True
                LOG.error("%s: checked out %s but the worktree is not clean", dest.name, sha[:12])
                return False
            LOG.warning("%s: fetched but cannot check out %s: %s", dest.name, sha[:12], checkout.stderr.strip())
    LOG.error("%s: unavailable (source %s, sha %s)", dest.name, source, sha[:12])
    return False


def checkout_is_pinned(dest: Path, sha: str) -> bool:
    """
    Report whether `dest` is exactly `sha` with nothing edited, deleted or added.

    `HEAD == sha` alone does not pin the bytes that get measured (review finding A6): edit a
    tracked file or drop an extra `.py` in, and stdout changes while the SHA still matches — so
    AC4's "same pin, same numbers" quietly stops being true. Untracked NON-Python junk
    (`.DS_Store`, an editor swapfile) cannot move a single measured number, so it is tolerated
    rather than turned into a spurious outage.
    """
    head: subprocess.CompletedProcess[str] = _run(["git", "-C", str(dest), "rev-parse", "HEAD"])
    if head.returncode != 0 or head.stdout.strip() != sha:
        return False
    status: subprocess.CompletedProcess[str] = _run(
        ["git", "-C", str(dest), "status", "--porcelain", "--untracked-files=all"]
    )
    if status.returncode != 0:
        LOG.error("%s: cannot read git status: %s", dest.name, status.stderr.strip())
        return False
    for line in status.stdout.splitlines():
        if not line.strip():
            continue
        name: str = line[3:].strip().strip('"')
        if line[:2] == "??":
            if name.casefold().endswith(".py"):
                LOG.error("%s: untracked Python file not covered by the pin: %s", dest.name, name)
                return False
            continue
        LOG.error("%s: tracked file modified since the pin: %s", dest.name, line.strip())
        return False
    return True


def measure_repo(url: str, sha: str, root: Path) -> RepoStats:
    """Walk every eligible `.py` file of a checked-out repo."""
    stats = RepoStats(name=repo_name(url), url=url, sha=sha, available=True)
    for path in iter_python_files(root):
        rel: str = path.relative_to(root).as_posix()
        try:
            with tokenize.open(path) as handle:
                head_lines: list[str] = [handle.readline() for _ in range(GENERATED_SCAN_LINES)]
        except (OSError, UnicodeDecodeError, SyntaxError) as exc:
            LOG.warning("%s/%s: unreadable (%s)", stats.name, rel, type(exc).__name__)
            stats.skipped_unparsable += 1
            continue
        if _looks_generated(head_lines):
            stats.skipped_generated += 1
            continue
        try:
            file_stats: FileStats = measure_file(path, rel_path=rel)
        except (SyntaxError, UnicodeDecodeError, ValueError, tokenize.TokenError) as exc:
            LOG.warning("%s/%s: unparsable (%s)", stats.name, rel, type(exc).__name__)
            stats.skipped_unparsable += 1
            continue
        stats.files.append(file_stats)
        stats.restatement_candidates += len(file_stats.restatement_hits)
        stats.restatement_code_like += sum(1 for h in file_stats.restatement_hits if h.code_like)
        stats.comment_blocks_examined += len(file_stats.comment_block_sizes)
    return stats


def _fmt_pct(value: float) -> str:
    """Percent with one decimal, locale-free, deterministic."""
    return f"{value * 100:.1f}%"


def render(repos: list[RepoStats], duplicates: dict[str, DuplicateStats]) -> list[str]:
    """Render the whole report as lines. Pure function of the inputs — AC4 lives here."""
    out: list[str] = []
    out.append("# tooprolix corpus measurement")
    out.append("")
    out.append(f"repos in lock: {len(repos)}")
    out.append("excluded dir components: " + ", ".join(sorted(EXCLUDED_DIRS)))
    out.append("excluded file suffixes: " + ", ".join(EXCLUDED_SUFFIXES))
    out.append(f"generated-header markers (first {GENERATED_SCAN_LINES} lines): " + ", ".join(GENERATED_MARKERS))
    out.append(
        f"shingle width k={SHINGLE_K}; candidate-index df cap={MAX_SHINGLE_DF}; difflib sample={DIFFLIB_SAMPLE} pairs"
    )
    out.append("")

    out.append("## 1. Prose share and block sizes per repo")
    out.append("")
    header: str = (
        f"{'repo':<28} {'files':>6} {'skip_bad':>8} {'skip_gen':>8} {'lines':>8} {'prose':>8} "
        f"{'share':>7} {'nonblank':>8} "
        f"{'doc_n':>6} {'doc_med':>7} {'doc_p90':>7} {'doc_max':>7} "
        f"{'cmt_n':>6} {'cmt_med':>7} {'cmt_p90':>7} {'cmt_max':>7}"
    )
    out.append(header)
    out.append("-" * len(header))
    for repo in repos:
        if not repo.measurable:
            out.append(f"{repo.name:<28} {repo.status_note}")
            continue
        doc: list[int] = sorted(s for f in repo.files for s in f.docstring_sizes)
        cmt: list[int] = sorted(s for f in repo.files for s in f.comment_block_sizes)
        total: int = sum(f.total_lines for f in repo.files)
        blank: int = sum(f.blank_lines for f in repo.files)
        prose: int = sum(f.prose_lines for f in repo.files)
        share: float = prose / total if total else 0.0
        strict: float = prose / (total - blank) if total - blank else 0.0
        out.append(
            f"{repo.name:<28} {len(repo.files):>6} {repo.skipped_unparsable:>8} "
            f"{repo.skipped_generated:>8} {total:>8} {prose:>8} "
            f"{_fmt_pct(share):>7} {_fmt_pct(strict):>8} "
            f"{len(doc):>6} {percentile(doc, 50):>7} {percentile(doc, 90):>7} "
            f"{max(doc, default=0):>7} "
            f"{len(cmt):>6} {percentile(cmt, 50):>7} {percentile(cmt, 90):>7} "
            f"{max(cmt, default=0):>7}"
        )
    out.append("")
    out.append(
        "share = prose_lines / total_lines (the issue's denominator: reproduces its "
        "published 48/53/42% for the three files it names)."
    )
    out.append(
        "nonblank = prose_lines / (total_lines - blank_lines). doc/cmt sizes are "
        "physical lines; med/p90 are nearest-rank."
    )
    out.append(
        "skip_bad = files the stdlib parser rejected, skip_gen = files with a machine-written "
        "header. Both are EXCLUDED from every column to their right, so they are printed beside "
        "the numbers they are missing from rather than only in a footnote."
    )
    out.append("")

    out.append("## 2. Per-file prose share distribution")
    out.append("")
    sub: str = (
        f"{'repo':<28} {'share_med':>10} {'share_p90':>10} {'share_max':>10} "
        f"{'files>50%':>10} {'skip_gen':>9} {'skip_bad':>9} {'trailing':>9}"
    )
    out.append(sub)
    out.append("-" * len(sub))
    for repo in repos:
        if not repo.measurable:
            out.append(f"{repo.name:<28} {repo.status_note}")
            continue
        shares: list[int] = sorted(round(f.prose_share * 1000) for f in repo.files if f.total_lines)
        over: int = sum(1 for s in shares if s > 500)
        out.append(
            f"{repo.name:<28} "
            f"{percentile(shares, 50) / 10:>9.1f}% "
            f"{percentile(shares, 90) / 10:>9.1f}% "
            f"{max(shares, default=0) / 10:>9.1f}% "
            f"{over:>10} {repo.skipped_generated:>9} {repo.skipped_unparsable:>9} "
            f"{sum(f.trailing_comments for f in repo.files):>9}"
        )
    out.append("")

    out.append("## 3. Tail of the block-size distribution")
    out.append("")
    tail: str = (
        f"{'repo':<28} {'blocks':>8} "
        + " ".join(f"{'>' + str(n) + 'ln':>8}" for n in BIG_BLOCK_LINES)
        + f" {'p99':>5} {'max':>5}"
    )
    out.append(tail)
    out.append("-" * len(tail))
    for repo in repos:
        if not repo.measurable:
            out.append(f"{repo.name:<28} {repo.status_note}")
            continue
        sizes: list[int] = sorted(b.size_lines for f in repo.files for b in f.blocks)
        counts: str = " ".join(f"{sum(1 for s in sizes if s > n):>8}" for n in BIG_BLOCK_LINES)
        out.append(f"{repo.name:<28} {len(sizes):>8} {counts} {percentile(sizes, 99):>5} {max(sizes, default=0):>5}")
    out.append("")
    out.append("### Block size in WORDS (the rival unit for the min-size cutoff)")
    out.append("")
    word_hdr: str = f"{'repo':<28} {'blocks':>8} {'w_med':>6} {'w_p90':>6} {'w_max':>6} " + " ".join(
        f"{'<' + str(n) + 'w':>7}" for n in MIN_WORD_GRID
    )
    out.append(word_hdr)
    out.append("-" * len(word_hdr))
    for repo in repos:
        if not repo.measurable:
            out.append(f"{repo.name:<28} {repo.status_note}")
            continue
        words: list[int] = sorted(b.size_words for f in repo.files for b in f.blocks)
        below: str = " ".join(f"{sum(1 for w in words if w < n):>7}" for n in MIN_WORD_GRID)
        out.append(
            f"{repo.name:<28} {len(words):>8} {percentile(words, 50):>6} "
            f"{percentile(words, 90):>6} {max(words, default=0):>6} {below}"
        )
    out.append("")
    out.append("'<Nw' = blocks a min-word cutoff of N would silence entirely.")
    out.append("")

    out.append("### 10 largest prose blocks per repo")
    out.append("")
    for repo in repos:
        if not repo.measurable:
            continue
        biggest: list[ProseBlock] = sorted(
            (b for f in repo.files for b in f.blocks), key=lambda b: (-b.size_lines, b.rel_path, b.start_line)
        )[:TAIL_TOP_N]
        out.append(f"{repo.name}:")
        for block in biggest:
            out.append(f"  {block.size_lines:>4} lines  {block.kind:<9} {block.rel_path}:{block.start_line}")
        out.append("")

    out.append("## 4. Duplicate candidates vs restatement candidates")
    out.append("")
    dup: str = (
        f"{'repo':<28} {'blocks':>8} {'exact_grp':>9} {'exact_pr':>9} "
        f"{'cand_pr':>9} {'capped_sh':>9} {'capped_bl':>9} {'restate':>8} {'commented':>9} "
        f"{'cmt_blocks':>10} {'restate/1k':>10}"
    )
    out.append(dup)
    out.append("-" * len(dup))
    for repo in repos:
        if not repo.measurable:
            out.append(f"{repo.name:<28} {repo.status_note}")
            continue
        stats: DuplicateStats = duplicates[repo.name]
        rate: float = (
            1000 * repo.restatement_candidates / repo.comment_blocks_examined if repo.comment_blocks_examined else 0.0
        )
        out.append(
            f"{repo.name:<28} {stats.blocks_total:>8} {stats.exact_groups:>9} "
            f"{stats.exact_pairs:>9} {stats.candidate_pairs:>9} "
            f"{stats.capped_shingles:>9} {stats.capped_blocks:>9} {repo.restatement_candidates:>8} "
            f"{repo.restatement_code_like:>9} "
            f"{repo.comment_blocks_examined:>10} {rate:>10.1f}"
        )
    out.append("")

    out.append("### Exact-duplicate pairs by size of the duplicated block")
    out.append("")
    size_hdr: str = f"{'repo':<28} " + " ".join(f"{str(n) + 'ln':>7}" for n in (1, 2, 3, 4, 5)) + f" {'6+ln':>7}"
    out.append(size_hdr)
    out.append("-" * len(size_hdr))
    for repo in repos:
        if not repo.measurable:
            continue
        by_size: dict[int, int] = duplicates[repo.name].exact_pairs_by_size
        cells: str = " ".join(f"{by_size.get(n, 0):>7}" for n in (1, 2, 3, 4, 5))
        rest: int = sum(v for k, v in sorted(by_size.items()) if k >= 6)
        out.append(f"{repo.name:<28} {cells} {rest:>7}")
    out.append("")

    out.append("### Most repeated exact prose (group size, block lines, sample)")
    out.append("")
    for repo in repos:
        if not repo.measurable:
            continue
        out.append(f"{repo.name}:")
        for copies, size, path, text in duplicates[repo.name].top_exact:
            out.append(f"  x{copies:<4} {size:>3}ln  {text!r} (first in {path})")
        out.append("")

    out.append("## 5. Threshold calibration: pairs above cutoff, by min block size")
    out.append("")
    for metric, key in (("Jaccard(3-shingles)", "jaccard"), ("difflib ratio", "difflib")):
        out.append(f"### {metric} — near-duplicate candidate pairs")
        out.append("")
        grid_hdr: str = f"{'repo':<28} {'min_ln':>6} " + " ".join(f"{'>=' + str(t):>9}" for t in JACCARD_GRID)
        out.append(grid_hdr)
        out.append("-" * len(grid_hdr))
        for repo in repos:
            if not repo.measurable:
                continue
            stats = duplicates[repo.name]
            grid: dict[tuple[int, float], int] = stats.jaccard_grid if key == "jaccard" else stats.difflib_grid
            for min_size in MIN_SIZE_GRID:
                cells = " ".join(f"{grid.get((min_size, t), 0):>9}" for t in JACCARD_GRID)
                out.append(f"{repo.name:<28} {min_size:>6} {cells}")
        out.append("")
        if key == "difflib":
            out.append(
                "difflib rows are scored on the first "
                f"{DIFFLIB_SAMPLE} candidate pairs (sorted order) per repo; "
                "sampled counts: "
                + ", ".join(f"{r.name}={duplicates[r.name].difflib_sampled}" for r in repos if r.measurable)
            )
            out.append("")

    out.append("### Jaccard(3-shingles) — cutoff in WORDS, not lines")
    out.append("")
    wgrid_hdr: str = f"{'repo':<28} {'min_w':>6} " + " ".join(f"{'>=' + str(t):>9}" for t in JACCARD_GRID)
    out.append(wgrid_hdr)
    out.append("-" * len(wgrid_hdr))
    for repo in repos:
        if not repo.measurable:
            continue
        wgrid: dict[tuple[int, float], int] = duplicates[repo.name].jaccard_word_grid
        for min_words in MIN_WORD_GRID:
            cells = " ".join(f"{wgrid.get((min_words, t), 0):>9}" for t in JACCARD_GRID)
            out.append(f"{repo.name:<28} {min_words:>6} {cells}")
    out.append("")

    out.append("### DECISION TABLE — conjunction cutoff (min lines AND min words) x threshold")
    out.append("")
    conj_hdr: str = f"{'repo':<28} {'cutoff':>9} " + " ".join(f"{'>=' + str(t):>9}" for t in JACCARD_GRID)
    out.append(conj_hdr)
    out.append("-" * len(conj_hdr))
    for repo in repos:
        if not repo.measurable:
            out.append(f"{repo.name:<28} {repo.status_note}")
            continue
        conj: dict[tuple[int, int, float], int] = duplicates[repo.name].conjunction
        for min_lines, min_words in CONJUNCTION_CUTOFFS:
            label: str = f"{min_lines}ln/{min_words}w"
            cells = " ".join(f"{conj.get((min_lines, min_words, t), 0):>9}" for t in JACCARD_GRID)
            out.append(f"{repo.name:<28} {label:>9} {cells}")
    out.append("")

    out.append(f"### Metric agreement on the SAME sampled pairs, cutoff {CALIBRATION_THRESHOLD}")
    out.append("")
    agree_hdr: str = f"{'repo':<28} {'sampled':>8} {'both':>8} {'jaccard_only':>13} {'difflib_only':>13}"
    out.append(agree_hdr)
    out.append("-" * len(agree_hdr))
    for repo in repos:
        if not repo.measurable:
            continue
        stats = duplicates[repo.name]
        out.append(
            f"{repo.name:<28} {stats.difflib_sampled:>8} {stats.agree_both:>8} "
            f"{stats.agree_jaccard_only:>13} {stats.agree_difflib_only:>13}"
        )
    out.append("")

    out.append("## 6. Corpus pins")
    out.append("")
    for repo in repos:
        out.append(f"{repo.sha}  {repo.status_note:<42} {repo.url}")
    out.append("")
    return out


def main(argv: list[str] | None = None) -> int:
    """Materialise the pinned corpus, measure it, print the report."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--lock", type=Path, required=True, help="path to corpus.lock")
    parser.add_argument(
        "--checkouts", type=Path, default=None, help="throwaway pin checkouts (default: <lock dir>/checkouts)"
    )
    parser.add_argument(
        "--mirror-dir", type=Path, default=None, help="read-only local clone sources (default: grandparent of the lock)"
    )
    parser.add_argument(
        "--inspect", default=None, metavar="REPO", help="instead of the report, list one repo's individual findings"
    )
    args = parser.parse_args(argv)
    logging.basicConfig(level=logging.INFO, stream=sys.stderr, format="%(levelname)s %(message)s")

    if sys.version_info[:2] < MIN_INTERPRETER:
        LOG.error(
            "need CPython >= %d.%d, got %d.%d — pre-3.12 tokenize hides identifiers inside "
            "f-strings and silently lowers the restatement counts (see MIN_INTERPRETER). "
            "Re-run with: uv run --python 3.14 python3 corpus/measure.py --lock %s",
            *MIN_INTERPRETER,
            *sys.version_info[:2],
            args.lock,
        )
        return 2

    lock: Path = args.lock.resolve()
    checkouts: Path = args.checkouts or lock.parent / "checkouts"
    mirror_dir: Path = args.mirror_dir or lock.parent.parent.parent

    try:
        entries: list[tuple[str, str]] = read_lock(lock)
    except (OSError, ValueError) as exc:
        LOG.error("cannot read %s: %s", lock, exc)
        return 2
    if not 5 <= len(entries) <= 10:
        LOG.error("corpus.lock must hold 5-10 repos, found %d", len(entries))
        return 2

    if args.inspect is not None:
        wanted: list[tuple[str, str]] = [e for e in entries if repo_name(e[0]) == args.inspect]
        if not wanted:
            LOG.error("%s is not in %s", args.inspect, lock.name)
            return 2
        url, sha = wanted[0]
        dest = checkouts / args.inspect
        if not ensure_checkout(url, sha, dest, mirror_dir):
            LOG.error("%s: cannot check out %s", args.inspect, sha[:12])
            return 2
        one: RepoStats = measure_repo(url, sha, dest)
        sys.stdout.write("\n".join(inspect_findings(one)) + "\n")
        return 0

    repos: list[RepoStats] = []
    duplicates: dict[str, DuplicateStats] = {}
    for url, sha in sorted(entries, key=lambda e: repo_name(e[0])):
        name: str = repo_name(url)
        dest: Path = checkouts / name
        if not ensure_checkout(url, sha, dest, mirror_dir):
            repos.append(RepoStats(name=name, url=url, sha=sha, available=False))
            duplicates[name] = DuplicateStats()
            continue
        LOG.info("measuring %s @ %s", name, sha[:12])
        repo: RepoStats = measure_repo(url, sha, dest)
        repos.append(repo)
        duplicates[name] = duplicate_stats([b for f in repo.files for b in f.blocks])

    sys.stdout.write("\n".join(render(repos, duplicates)) + "\n")
    # Fail loud, but distinguish the two failures. A pin that could not be
    # checked out means numbers are MISSING -> exit 1. A pin that holds no
    # Python at all is a measured fact, not a tool failure: it is shouted in
    # stdout, in stderr and in REPORT.md, so the report is complete -> exit 0.
    for repo in repos:
        if not repo.measurable:
            LOG.error("%s: %s", repo.name, repo.status_note)
    return 0 if all(r.available for r in repos) else 1


if __name__ == "__main__":
    raise SystemExit(main())
