# Use bash from PATH instead of /bin/sh — uniform behaviour on macOS/Linux/CI.
SHELL := /usr/bin/env bash
# -e fail on first error, -u error on unset vars, -o pipefail propagate pipe failures.
.SHELLFLAGS := -euo pipefail -c
# `make` with no target shows help, not the first recipe.
.DEFAULT_GOAL := help

UV ?= uv
# The toolchain is pinned in rust-toolchain.toml, so plain `cargo` already resolves to 1.97.0.
CARGO ?= cargo

# Paths the Python gates run on. This is a Rust project with two Python corners: the throwaway
# corpus measurement, and `scripts/coverage_report.py`, which reads the coverage reports.
#
# ⚠️ These are LINT paths and they are deliberately NOT the coverage denominator, which is
# `[tool.coverage.run] source` in pyproject.toml and lists `corpus` alone. The overlap is a
# coincidence of two tools looking at the same directory for different reasons: lint asks "is this
# file well formed", coverage asks "how much of this file did the tests run". Putting `tests/unit`
# in the second one would make the percentage climb every time someone writes more test code.
LINT_PATHS ?= corpus scripts tests/unit
TY_PATHS ?= corpus scripts tests/unit

# Corpus measurement inputs.
LOCK ?= corpus/corpus.lock

# Where the two coverage tools drop their machine-readable reports and cargo puts its instrumented
# build. Under `target/`, which `.gitignore` already covers, so a coverage run leaves nothing behind
# in the working tree. Nothing generated by these targets is committed.
COV_DIR ?= target/coverage

.PHONY: help lint.fix lint.check type test corpus.measure \
	rust.fmt rust.fmt.check rust.lint rust.test rust.doc rust.build \
	rust.cov py.cov cov

help: ## Show this help
	@awk 'BEGIN {FS = ":.*##"; printf "Usage: make <target>\n\nTargets:\n"} \
	/^[a-zA-Z_.-]+:.*##/ {printf "\033[36m%-16s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

# `--only-group`, not `--group`, in all three Python gates below. It installs the group WITHOUT
# building this project. This is a LIVE constraint, not a precaution: the maturin `[build-system]` is
# in pyproject.toml now, so `--group` makes uv attempt an editable build of the Rust extension and
# every Python gate dies with "'--editable'] returned non-zero exit status 1". Do not "fix" these to
# `--group`; verified consequence, not style.
lint.fix: ## Format and autofix the Python code with ruff (LINT_PATHS)
	@$(UV) run --only-group lint ruff format $(LINT_PATHS)
	@$(UV) run --only-group lint ruff check --fix $(LINT_PATHS)

lint.check: ## Check formatting and lint rules with ruff (LINT_PATHS) — CI mode
	@$(UV) run --only-group lint ruff format --check $(LINT_PATHS)
	@$(UV) run --only-group lint ruff check $(LINT_PATHS)

type: ## Check types with ty (TY_PATHS)
	@# Both groups, because TY_PATHS includes tests/unit and those files import pytest.
	@# With only the `type` group, ty cannot resolve that import and reports
	@# `unresolved-import` — which looked green here only because a leftover .venv already
	@# had pytest in it. From a clean checkout, i.e. in every isolated CI job, it fails.
	@$(UV) run --only-group type --only-group test ty check $(TY_PATHS)

test: ## Run the Python tests (pytest, tests/unit)
	@$(UV) run --only-group test pytest

corpus.measure: ## Measure the pinned prose corpus and print the distributions
	@uv run python3 corpus/measure.py --lock $(LOCK)

# The four Rust gates below are one CI job each (cargo-fmt / cargo-clippy / cargo-test /
# cargo-doc) and are what every later task has to keep green. `--locked` everywhere: Cargo.lock
# is committed, so a gate that silently re-resolved it would not be testing the code CI builds.
#
# ⚠️ `FIND_PYTHON` used to live here and is GONE with the pyo3 boundary (epic 2 Decisions #19.1).
# It resolved an interpreter with `uv python find` because pyo3-ffi's build script located CPython
# by scanning PATH, so every cargo command that compiled the crate silently depended on whichever
# `python3` came first. No cargo command here compiles against an interpreter any more — `cargo
# tree | grep -c pyo3` is 0 — so the lookup would only be a step that can fail for a reason no gate
# cares about. The CI steps that installed a managed Python for it went in the same change.

rust.fmt: ## Format the Rust code with rustfmt
	@$(CARGO) fmt

rust.fmt.check: ## Check Rust formatting without writing (CI mode)
	@$(CARGO) fmt --check

# 🔴 NO `--features python` ON EITHER, and the reason the flag existed is worth keeping.
# Until epic 2 Decisions #19.1 the pyo3 boundary sat behind an off-by-default feature, and with the
# feature off `cargo test` compiled none of the 5 boundary tests in src/lib.rs: measured 2026-07-27,
# `make rust.test` stayed **exit 0** and reported **128 passed** where it had been 133 — green by
# testing less, with no other signal. The flag plus a `compile_error!` in src/lib.rs held that line.
#
# The feature, the boundary, the 5 tests and the `compile_error!` are all gone now, so there is no
# flag left to forget. The count drops from 218 to 213 in the same change, and that drop is the
# 5 boundary tests and nothing else. What replaces the guard is `scripts/install-smoke.sh`, which
# installs each built artifact and runs the command — mutation-proved against a wheel with its
# executable removed, because "the guard changed shape" is exactly where this epic has been bitten.

rust.lint: ## Lint the Rust code with clippy, warnings are errors
	@$(CARGO) clippy --all-targets --locked -- -D warnings

rust.test: ## Run the Rust tests (unit + doctests)
	@$(CARGO) test --locked

# Rustdoc as a GATE, not a byproduct. `cargo doc` reports a broken intra-doc link as a warning and
# still exits 0, so before this target the crate carried 5 of them on `main` and every gate was
# green. `RUSTDOCFLAGS="-D warnings"` is what turns them into exit 101.
#
# `--document-private-items` is NOT free and the justification here is measured, not inherited.
# Earlier revisions of the audit task claimed both variants gave the same single warning, so the
# flag "opens nothing". Measured 2026-07-29 at 962678d: the plain run reports 5 diagnostics and the
# flag reports 6. The one it adds is a genuinely dangling link -- `render_failures` in the rustdoc
# of `python_files`, naming a function that exists nowhere in `src/`. Without the flag rustdoc never
# documents the private `python_files` at all, so it never resolves the link and the dead reference
# stays invisible. Mutation-proved both ways: with the link broken and the flag dropped, the gate
# goes back to exit 0.
#
# `--no-deps`: we gate OUR docs, not our dependencies'.
rust.doc: ## Build the rustdoc and fail on any warning (broken or private intra-doc links)
	@RUSTDOCFLAGS="-D warnings" $(CARGO) doc --locked --no-deps --document-private-items

# The linkage guard on the shipped binary. It is what proves `tooprolix` runs where no interpreter
# does — the promise the wheel makes by carrying a native executable instead of an extension module.
#
# ⚠️ It used to be called `rust.build.nopython`, the "other half" of a pyo3 feature gate that no
# longer exists: with `--features python` on every other Rust gate, this was the only thing in CI
# that ever compiled the crate with the feature OFF. Epic 2 Decisions #19.1 deleted the feature, so
# there is no longer another half — this is now simply THE build.
#
# 🔴 IT ASSERTS THE LINKAGE, NOT THE COMPILATION, and the difference is the whole guard. `cargo
# build` alone cannot tell "it compiles" from "it needs no interpreter". Measured 2026-07-27, back
# when the feature existed: with `default = ["python"]` and an interpreter on PATH the build step
# exits **0** and blesses a binary whose `otool -L` reads
#
#     /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/Python
#
# 🔴 AND THE MUTATION THAT PROVES IT IS NOT THE OBVIOUS ONE. Adding `pyo3 = "0.29.0"` back to
# `[dependencies]` leaves this target **GREEN** — measured 2026-07-31, `otool -L` still lists only
# `libSystem.B.dylib`, because rustc links no crate nothing references. The comment here claimed
# that declaration was the mutation, and the claim was false; it is corrected rather than quietly
# dropped, because a guard whose stated mutation passes is a guard nobody has actually tested.
#
# The mutation that DOES turn it red is the declaration plus a real `use`: with `pyo3` in
# `[dependencies]` and a `pyo3::Python::attach(...)` in `src/lib.rs`, this target fails with
#
#     /opt/homebrew/opt/python@3.14/Frameworks/.../Python (compatibility version 3.14.0, ...)
#     error: ... links the Python library above; the wheel promises a self-contained binary.
#
# which is also the shape a real regression takes — nobody re-adds the dependency without using it.
#
# `otool -L` on macOS, `ldd` on Linux (both CI runners and this laptop are covered; nothing else
# runs it). Deliberately NOT a `cargo tree`/feature-graph check: that grades a proxy for the
# artifact rather than the artifact.
#
# 🔴 THE PATH COMES FROM CARGO, and hardcoding it was an instance of the very defect this target
# exists to close. `target/debug/tooprolix` is not where cargo necessarily writes: both
# `CARGO_TARGET_DIR` and `build.target-dir` in `.cargo/config.toml` move it. Measured 2026-07-27
# with `default = ["python"]` and `CARGO_TARGET_DIR` set elsewhere — cargo compiled a
# libpython-linked binary into the alternate directory while this recipe read a stale clean binary
# left over at `target/debug/`, printed `ok: ... links no libpython` and exited 0. The stale file is
# what made it silent. `--message-format=json` makes cargo name the executable it just linked, so
# the guard reads the artifact it actually produced and no reconstruction can drift from it.
#
# An empty listing is treated as a FAILURE, not a pass, and so is cargo reporting no executable at
# all. A missing or renamed `otool`/`ldd` would otherwise make the grep match nothing and the guard
# report success without having looked.
rust.build: ## Build the binary and prove it links no libpython (it must run without an interpreter)
	@json="$$($(CARGO) build --locked --message-format=json)"; \
	rc=$$?; \
	if [ $$rc -ne 0 ]; then exit $$rc; fi; \
	binary="$$(printf '%s\n' "$$json" | sed -n 's/.*"executable":"\([^"]*\)".*/\1/p' | tail -1)"; \
	if [ -z "$$binary" ]; then \
		echo "error: cargo reported no executable; the linkage guard has nothing to inspect." >&2; \
		exit 1; \
	fi; \
	case "$$(uname -s)" in \
		Darwin) linked="$$(otool -L $$binary)" ;; \
		*)      linked="$$(ldd $$binary)" ;; \
	esac; \
	if [ -z "$$linked" ]; then \
		echo "error: could not read the dynamic dependencies of $$binary; the linkage guard did not run." >&2; \
		exit 1; \
	fi; \
	if printf '%s\n' "$$linked" | grep -i python; then \
		echo "error: $$binary links the Python library above; the wheel promises a self-contained binary." >&2; \
		echo "       A dependency that is merely declared is fine; one that is USED links it in." >&2; \
		exit 1; \
	fi; \
	printf '%s\n' "$$linked"; \
	echo "ok: $$binary links no libpython"

# -----------------------------------------------------------------------------------------------
# Coverage. Two numbers, never one: the Rust crate is the product and `corpus/` is throwaway
# research tooling, so a combined percentage would average two things measured against unrelated
# denominators and look more precise than either (EPIC scope guard).
#
# These targets PRINT a number and write a JSON report to `$(COV_DIR)`; there is no badge. The
# repository is private until the PyPI flip so no badge host can read it, and the projects worth
# comparing against publish none either — ruff, uv, tokio, serde, ripgrep, cargo, maturin, polars,
# httpx and starlette all measure coverage without advertising it. Revisit at publication.
#
# The value here is not the percentage, it is `scripts/coverage_report.py` refusing a report that
# measured less than it claims: drop `branch = true`, orphan a module from the `mod` tree, or let a
# file fall out of coverage.py's discovery, and the number goes UP with nothing else to show for it.
# Tasks 9-11 audit against these figures, so a silently shrinking denominator is the failure that
# matters.
#
# There is deliberately NO `--fail-under` / threshold on either target. A threshold before those
# audits would be a number picked to match today's code rather than a decision, and picking it is
# the user's call once the audits have said what the uncovered surface actually is.
#
# ⚠️ What these numbers do NOT cover, said out loud because a percentage implies it measured
# everything it could:
#   - `build.rs` is a BUILD SCRIPT. cargo compiles and runs it on the host before the crate exists,
#     so `cargo llvm-cov` does not instrument it and it appears in no row of the Rust report. Its
#     ~190 lines of civil-date arithmetic and git containment are therefore unmeasured, not 100%.
#   - `tests/volume_corpus.rs`'s `volume_finds_something_on_the_corpus` is `#[ignore]`d (it needs
#     `corpus/checkouts/` on disk), so the lines only it reaches count as uncovered. That is the
#     truth about a test that does not run in CI, and un-ignoring it here would be buying coverage
#     with a gate that cannot run.
#   - `tests/adversarial_bench.rs`'s `adversarial_headers_stay_within_the_line_rate_budget` is the
#     SECOND `#[ignore]`d test, added 2026-07-30, and it takes the `ignored` count from 1 to 2. Said
#     out loud rather than absorbed: a rising `ignored` is a finding by this epic's own verification
#     policy. It is ignored because it is a wall-clock instrument — it needs `--release` to mean
#     anything (a debug build measures the profile, not the algorithm) and it writes 2 000 files
#     twice over. It PASSES: 2.59-2.87 s against a 5.000 s budget at 100 000 lines. It did not before
#     the `shingles` change in the same commit, which is the measurement that motivated that change.
#     Its two non-ignored halves, `the_generated_headers_are_adversarial_by_construction` and
#     `the_timed_trees_are_the_ones_the_recorded_numbers_were_measured_on`, DO run in CI, so neither
#     the fixture nor the timed trees can rot unnoticed while only the timed half is skipped.
#   - 🔴 THE COVERAGE RUN IS NOT THE TEST RUN. `cargo llvm-cov` skips doctests unless `--doctests`
#     is passed, so `make rust.cov` instruments **188 of the 194 tests** `make rust.test` runs — the
#     6 doctests (`test result: ok. 6 passed`, the `Doc-tests tooprolix` target) are absent from it
#     entirely, and code reached only by a doctest is reported uncovered.
#     `--doctests` is NOT available here, and that is measured rather than assumed: on the pinned
#     stable 1.97.0 it fails with `error: 2 nightly options were parsed`, because cargo-llvm-cov
#     drives rustdoc with `-Z unstable-options --persist-doctests`. Getting those 6 into the number
#     would mean moving the whole repository to a nightly toolchain, which is a far larger decision
#     than a coverage figure. So they stay out, stated rather than silent.
#   - Rust BRANCH coverage is not reported at all: the `Branches` column of llvm-cov reads `-` on
#     the pinned stable 1.97.0 (it needs a nightly-only flag). The Rust number is LINE coverage. The
#     Python number has `branch = true` and folds branches into its figure — the two are reported
#     separately for this reason among others, and are not comparable to each other.

rust.cov: ## Measure Rust line coverage and print it
	@mkdir -p $(COV_DIR)
	@$(CARGO) llvm-cov --locked --summary-only \
		--json --output-path $(COV_DIR)/llvm-cov.json
	@$(UV) run --no-project python3 scripts/coverage_report.py \
		--report $(COV_DIR)/llvm-cov.json --format llvm-cov

py.cov: ## Measure Python coverage of corpus/ and print it
	@mkdir -p $(COV_DIR)
	@# `--cov` with no argument means "use [tool.coverage.run] from pyproject.toml", which is where
	@# the denominator (`source = ["corpus"]`, NOT tests/unit) and `branch = true` are pinned and
	@# commented. Passing paths here instead would put the denominator in two places.
	@$(UV) run --only-group test pytest --cov --cov-report=term \
		--cov-report=json:$(COV_DIR)/coverage.json
	@$(UV) run --no-project python3 scripts/coverage_report.py \
		--report $(COV_DIR)/coverage.json --format coverage.py

cov: rust.cov py.cov ## Measure coverage for both languages and print both numbers
