"""
Guards for what `corpus/measure.py` lets into the denominator.

Every ratio in `corpus/REPORT.md` — prose share, block tails, duplicate counts, restate/1k —
divides by the set of files these filters admit. A bypass here does not produce an obviously
wrong number, it produces a plausible wrong number, which is worse. Review findings A3, A5, A6.

Run: make test
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import measure
import pytest


def write(root: Path, rel: str, text: str = "x = 1\n") -> Path:
    """Create a file (and parents) under `root`."""
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def found(root: Path) -> set[str]:
    """POSIX-relative paths `iter_python_files` admits."""
    return {p.relative_to(root).as_posix() for p in measure.iter_python_files(root)}


class TestExclusionBypasses:
    """Compare-before-normalise let three classes of non-source into the denominator (A3)."""

    def test_egg_info_is_matched_as_a_path_component_not_a_filename(self, tmp_path: Path) -> None:
        """
        `pkg.egg-info/generated.py` is packaging metadata, not this repo's prose.

        The old check asked whether the FILE was named `*.egg-info`, which no `.py` file ever
        is, so the whole directory sailed through.
        """
        write(tmp_path, "pkg.egg-info/generated.py")
        write(tmp_path, "src/real.py")
        assert found(tmp_path) == {"src/real.py"}

    def test_excluded_directories_match_case_insensitively(self, tmp_path: Path) -> None:
        """
        `Vendor/` is vendored code just as much as `vendor/` is.

        macOS and Windows checkouts routinely differ in case; a case-sensitive compare means
        the same repo measures differently on two machines.
        """
        write(tmp_path, "Vendor/lib.py")
        write(tmp_path, "Third_Party/dep.py")
        write(tmp_path, "src/real.py")
        assert found(tmp_path) == {"src/real.py"}

    def test_symlink_into_an_excluded_tree_is_judged_by_its_target(self, tmp_path: Path) -> None:
        """A link named `src/lib.py` pointing at `vendor/lib.py` is still vendored code."""
        write(tmp_path, "vendor/lib.py")
        write(tmp_path, "src/real.py")
        (tmp_path / "src" / "lib.py").symlink_to(tmp_path / "vendor" / "lib.py")
        assert found(tmp_path) == {"src/real.py"}

    def test_the_same_file_reached_twice_is_counted_once(self, tmp_path: Path) -> None:
        """Two links to one file would otherwise double its prose in every total."""
        write(tmp_path, "src/real.py")
        (tmp_path / "src" / "alias.py").symlink_to(tmp_path / "src" / "real.py")
        assert found(tmp_path) == {"src/real.py"}

    def test_ordinary_source_survives_all_of_it(self, tmp_path: Path) -> None:
        """
        The filter must not become so eager that it eats the corpus.

        `vendor` as a SUBSTRING of a real package name (`vendored_utils`) is not an exclusion —
        only a whole path component is.
        """
        write(tmp_path, "src/pkg/module.py")
        write(tmp_path, "tests/test_thing.py")
        write(tmp_path, "vendored_utils/helper.py")
        assert found(tmp_path) == {"src/pkg/module.py", "tests/test_thing.py", "vendored_utils/helper.py"}


class TestGeneratedHeaderAnchoring:
    """A bare substring match excluded hand-written files from every denominator (A5)."""

    def test_prose_mentioning_generation_is_not_a_generated_file(self) -> None:
        """The exact docstring from the review finding must NOT exclude the file."""
        lines = ['"""Utilities for issue tracking.', "", "IDs are generated by the server.", '"""', ""]
        assert measure._looks_generated(lines) is False

    def test_a_prose_sentence_ending_in_do_not_edit_is_not_a_header(self) -> None:
        """Advice inside a docstring is not a machine header."""
        lines = ['"""Config loader.', "", "This file is the source of truth, so do not edit the copy.", '"""']
        assert measure._looks_generated(lines) is False

    @pytest.mark.parametrize(
        "line",
        [
            "# Code generated by protoc-gen-go. DO NOT EDIT.",
            "#  @generated by the openapi generator",
            "# DO NOT EDIT — autogenerated",
            '"""Generated by datamodel-code-generator."""',
        ],
    )
    def test_real_machine_headers_are_still_caught(self, line: str) -> None:
        """Anchoring must not stop the detector detecting."""
        assert measure._looks_generated([line, "", "x = 1"]) is True


class TestCheckoutIntegrity:
    """`HEAD == sha` alone does not pin the bytes that get measured (A6)."""

    @staticmethod
    def _repo(tmp_path: Path) -> tuple[Path, str]:
        """Build a one-commit git repo; return its path and HEAD sha."""
        root = tmp_path / "repo"
        root.mkdir()
        env = {
            "GIT_AUTHOR_NAME": "t",
            "GIT_AUTHOR_EMAIL": "t@t",
            "GIT_COMMITTER_NAME": "t",
            "GIT_COMMITTER_EMAIL": "t@t",
        }
        write(root, "mod.py")
        for args in (["init", "-q"], ["add", "-A"], ["commit", "-qm", "c"]):
            subprocess.run(["git", "-C", str(root), *args], check=True, env={"PATH": "/usr/bin:/bin", **env})
        sha = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "HEAD"], capture_output=True, text=True, check=True
        ).stdout.strip()
        return root, sha

    def test_a_clean_pinned_checkout_is_accepted(self, tmp_path: Path) -> None:
        """The happy path must still pass, or the guard is just an outage."""
        root, sha = self._repo(tmp_path)
        assert measure.checkout_is_pinned(root, sha) is True

    def test_a_modified_tracked_file_is_rejected(self, tmp_path: Path) -> None:
        """
        Editing a measured file changes stdout while HEAD still matches the pin.

        That is precisely the hole: AC4 claims the SHA guarantees the numbers, and it does not
        unless the worktree is clean.
        """
        root, sha = self._repo(tmp_path)
        (root / "mod.py").write_text("x = 2  # edited\n", encoding="utf-8")
        assert measure.checkout_is_pinned(root, sha) is False

    def test_an_untracked_python_file_is_rejected(self, tmp_path: Path) -> None:
        """An extra `.py` adds prose that no pin accounts for."""
        root, sha = self._repo(tmp_path)
        write(root, "extra.py")
        assert measure.checkout_is_pinned(root, sha) is False

    def test_untracked_non_python_junk_is_tolerated(self, tmp_path: Path) -> None:
        """`.DS_Store` cannot change a single measured number; failing on it is noise."""
        root, sha = self._repo(tmp_path)
        (root / ".DS_Store").write_bytes(b"\x00")
        assert measure.checkout_is_pinned(root, sha) is True

    def test_a_different_sha_is_rejected(self, tmp_path: Path) -> None:
        """The pin still has to be the pin."""
        root, _ = self._repo(tmp_path)
        assert measure.checkout_is_pinned(root, "0" * 40) is False
